- README.md
- package.json
> docs: Update minimum Node version

- .firebaserc
- .gitignore
- firebase.json
Latest version here: https://pokeapi-static-website.firebaseapp.com/
> Add firebase config

- src/docs/pokemon.json
Nothing to add, really! Just a very quick PR to fix a typo I found.
> Fix single letter typo!

- src/docs/utility.json
> [docs] Add missing version field to FlavorText

- src/docs/evolution.json
> Add missing square brackets (#32)

- src/pages/about.html.js
> Change Veekun link (#42)

- src/components/LayoutFooter/LayoutFooter.js
- src/pages/about.html.js
- src/pages/docs/v1.html.js
- src/pages/docs/v2.html.js
- Fixed phalt.co dead links
- Changed contributors link to a more relevant one, in my opinion
- Fixed some typos
- Light changes to the v1 page
- Other text related fixes
- Added Pokepy to wrapper list
> Add Pokepy to official wrappers list + some documentation fixes

- src/docs/locations.json
location is of type Location instead of Region
> Fix wrong NamedAPIResource type in LocationArea

- src/components/ApiExplorer/ApiExplorer.js
> fix: Add missing return statement

- src/components/ApiExplorer/ApiExplorer.js
- src/docs/index.js
- src/docs/pokemon.json
- src/pages/docs/v2.html.js
Resolves #45.
This will fix the broken sidebar table of contents links and add Resource Lists and Utility sub-sections to the TOC.
I left the Berry Firmnesses description blank because I have no idea what Berry Firmnesses do or what they affect, and I couldn't find that info online.
> Fix v2 docs errors (#45)

- src/components/LayoutFooter/LayoutFooter.js
Updated the copyright date on the websites footer.
> Updated Copyright on website

- src/pages/index.js
Just checked and among the last 30 days, we've served 23 500 000 calls.
> Bump invocations' number

- src/docs/encounters.json
- src/docs/items.json
- src/docs/moves.json
- src/docs/pokemon.json
> Fixes incorrect types in documentation

- src/components/ApiExplorer/Input.js
- src/components/ApiExplorer/Input.module.scss
- src/components/Footer/Footer.js
- src/components/Footer/Footer.module.scss
- src/components/JsonViewer/JsonViewer.module.scss
- src/components/JsonViewer/tomorrow.json
- src/constants.scss
- src/docs/resource-lists.json
- src/global.scss
- src/pages/about.js
- src/pages/about.module.scss
- src/pages/docs/v1.js
- src/pages/docs/v2.js
- src/pages/docs/v2.module.scss
- src/pages/index.js
- src/pages/index.module.scss
- static.config.js
In order to celebrate almost 2000 stars on our main Github repo, I made some changes to our pokeapi.co frontend to make it more appealing. I also modified some sections of the `/about` page, to give more credits to all the people who have worked/are working on the PokeAPI project.
Check out the changes here: https://staging.pokeapi.co
> Style redesign and credits

- src/docs/pokemon.json
https://staging.pokeapi.co/docs/v2#pokemon-location-areas
> Add location-area endpoint

- alerts.json
- src/components/Header/Header.js
- src/global.scss
- src/pages/docs.js
- src/pages/docs/graphql.js
- static.config.js
Advertise new graphql & remove gen-8 banners
> Advertise new graphql & remove gen-8 banners

- src/pages/docs/v2.js
Added Crystal wrapper library to the list of wrapper libraries.
[Repo](https://github.com/henrikac/pokeapi)
> added crystal wrapper library

- src/pages/docs/v2.js
I simply added a reference to the asynchronous wrapper that I have written in Python, I would very much appreciate if it would get added
> Add aiopokeapi to wrappers

- src/components/ApiExplorer/ApiExplorer.js
- src/docs/moves.json
- src/docs/pokemon.json
- src/pages/docs/v2.js
- src/pages/index.js
- static.config.js
Should fix https://github.com/PokeAPI/pokeapi/issues/682
> Dont render undefined

- src/pages/docs/v2.js
Closed #112 and created a new pull request because it was easier.
> Added pokeapi-reactor to docs

- src/pages/about.js
> Typo fix in About page

- src/pages/docs/graphql.js
- src/pages/docs/v2.js
- src/pages/index.js
Update calls/state free and OSS/add sec section/clarify Slack status/clarify graphql beta status
> General update

- alerts.json
Hi I wanted to add an _alert_ to showcase the fact that the project is turning 10! If you have other suggestions feel free to comment down below!
> Pokeapi turning 10

- src/pages/docs/v2.js
Hey everyone I made a Golang API wrapper for the PokeAPI v2. I would appreciate it if you could add it to the list of wrapper libraries for the PokeAPI.  Check it out and let me know what you think.  https://github.com/JoshGuarino/PokeGo
> add a golang wrapper library
