PokeAPI/pokeapi.co

- src/docs/pokemon.json
Addresses the issue raised in PokeAPI/pokeapi.co#19.
The documentation now states the proper units for height (decimetre) and weight (hectogram).
For example, for Garchomp (445):
- 19 decimetres = 1.9 metres
- 950 hectograms = 95 kilograms
> clarified units for Pokémon height and weight

- src/components/Layout.global.scss
This resets sanitize.css's weird design choices regarding cursors, which
doesn't match any UX behaviour that I've seen before (sanitize.css is
otherwise quite good).
> fix: Put the cursors back to normal

- .circleci/config.yml
In preparation for deploying both the website and the API data to a single Firebase project, update this CircleCI to store a tarball of the `public` directory as an artifact and trigger a build of the `deploy` repository on CircleCI.
> Update CircleCI config for deploying to Firebase

- .circleci/config.yml
Everything works and successfully deployed to Firebase, except the website files got nested in an extra folder.
> fix: In CircleCI, tar only the contents of 'public'

- src/components/ApiExplorer/ApiExplorer.js
The "Try it now!" search yields an error for all searches:
An error occurred: "TypeError: Failed to execute 'fetch' on 'Window': The provided value 'force-cached' is not a valid enum value of type RequestCache."
Reason: the value for the fetch() property 'cached' contains a typo: 'force-cached' vs. 'force-cache' which is correct according to https://fetch.spec.whatwg.org/
> fixes fetch error on homepage for "Try it now!" searches

- src/docs/locations.json
Both location and location-area accept names as well as ids
> Fix missing name parameter in location endpoints

- src/components/ApiExplorer/ApiExplorer.js
And display the resource URL when a name is not available, instead of 'undefined'.
> Fix API Explorer 404 error message on (#41)

- src/docs/pokemon.json
@Finrod_Amandil suggested a couple of changes to the docs in PokeAPI/pokeapi#401 to clarify the confusion between Pokemon and PokemonForm resources. I think they look good. Should we merge them?
> Add suggested changes to Pokemon/Form descriptions

- src/docs/moves.json
- src/docs/pokemon.json
Found these while trying to generate TypeScript definitions. I haven't tried generating docs from this yet.
> Fix some errors in docs

- src/components/Alerts/Alerts.js
- src/pages/docs/v2.html.js
Added my Ruby gem wrapper `Poke-Api-V2` (https://github.com/rdavid1099/poke-api-v2) (https://rubygems.org/gems/poke-api-v2) to list of wrappers.
_NOTE_: I added a `return null;` to Alerts.js on line 64 because Gatsby was not allowing anything to render without that in the local dev environment. If you would like me to revert that to a simple `return;` just tell me. Thank you.
> Add Poke-Api-V2 ruby gem wrapper to list of wrappers in docs

- src/pages/docs/v2.html.js
I created a wrapper library targeting .Net Standard 2.0 that just got published for use. I'll submit an additional PR to add this to the list of wrappers to the readme as well in the main repo.
> add .Net Standard PokeApiNet wrapper

- .gitignore
- src/pages/docs/v2.html.js
Added my wrapper, [pokeapi-go](https://github.com/mtslzr/pokeapi-go), to the Docs pages.
Also added `yarn.lock` to .gitignore so it didn't commit.
> Added Go wrapper to Docs

- .circleci/config.yml
This PR allows invoking in a conditional manner a new _deploy_ job present in the `PokeAPI/deploy` CircleCI configuration. This job will automatically deploy the `pokeapi.co` website to our productive environment (pokeapi.co) or to a new staging environment.  The job will be invoked only when the `master` or `staging` branches of this repository are pushed to. If the `master` is getting pushed then the `master` branch will be deployed in the productive environment. Viceversa, if the `staging` branch is pushed, then the `staging` branch will be deployed in the staging environment. 
A more descriptive and general overview is detailed in this https://github.com/PokeAPI/pokeapi/pull/488 PR.
---
This PR is linked to the following PRs: 
- https://github.com/PokeAPI/deploy/pull/10  
- …
> Enable staging deployment

- src/docs/pokemon.json
Fixes: #86
Added in documentation for .is_legendary and .is_mythical under "Pokemon Species."
Let me know if this looks okay.
> Add is_legendary and is_mythical documentation

- src/docs/moves.json
Also fixes a link to `MoveCategory` type in `MoveMetaData.category`
> Rename ModelName to MoveCategory

- src/pages/status.js
Free Updown.io credits using pokeapi.co@gmail.com have been used.
This PR changes the links to the same status pages created using my Updown.io account.
> Update updown.io links

- src/pages/docs/v2.js
Hello !
I wrote a wrapping library covering the whole PokeApi v2 in Rust, with auto caching.
Since there is no such Rust library referenced in the documentation on the website, I was wondering if referencing mine was possible.
This is what this PR is for. I just added the informations in the corresponding array. 
Please find attached a screenshot of the result.
Please let me know if this is OK for you.
I stay available if you have some remarks.
Have a good day !
> Reference Rust library in api documentation

- src/docs/pokemon.json
The doc displays the wrong data type for field "types" of PokemonSprite.
Example:
This is the result of query:  https://pokeapi.co/api/v2/pokemon-form/1
It should be a list of PokemonFormType but instead it displays:
Visible changes after the fix:
> fix: PokemonSprite.types wrong typing in the doc

- src/components/ApiExplorer/ApiExplorer.js
Many people seem confused about the difference between our `pokemon` and `pokemon-species` endpoints. Some don't even know that `pokemon-species` is an endpoint and that should be the one to query first when retrieving full Pokemon data.
Maybe this hint on the homepage will help people discover the endpoint.
> Use different endpoint for hints

- src/pages/docs/v2.js
I've written a [wrapper to the api in Scala 3](https://github.com/juliano/pokeapi-scala), this pr adds the [already published](https://search.maven.org/artifact/io.github.juliano/pokeapi-scala_3/0.1.0/jar) library to the list of wrapper libraries.
> Add pokeapi-scala to docs

- src/App.js
- src/pages/index.js
Currently the server costs for running PokeAPI are around $43 USD a month.
This small advert would help cover the costs almost entirely (based on the page views).
> Add Google adsense

- src/docs/pokemon.json
The two missing fields "highest_stat" and "descriptions" have been added to the documentation of the "Characteristic" type.
> Document missing fields in the "Characteristic" type

- src/docs/moves.json
- src/pages/docs/v2.js
I check every link on pages e fix a bulbapedia in "Move Ailments".
I found this link to 404 page `https://phalt.github.io/posts/if-you-have-data-they-will-consume-it/` in the explanation of the change from v1 to v2.
And finally, add a elixir wrapper that I created.
My vscode linter tweaked some lines in other array elements. 😅
> Add an elixir lib and fix doc link

- README.md
The hyperlink to `pokeapi.co` is interpreted as a relative path, leading to a GitHub 404 page instead of the actual PokeAPI website when clicked from the README.
Updated the URL to include the `https://` prefix, ensuring proper redirection.
With this correction, anyone reading the README will be directed to the correct PokeAPI website upon clicking the link.
> Fix Broken Hyperlink to pokeapi.co in README

- src/components/Footer/Footer.js
- src/pages/about.js
Context:
- My personal website is no longer this, it is just my Github page.
- The contributors page has it's own link now on GitHub.
> Update website and link to contributors

- src/docs/pokemon.json
Added documentation for the `PokemonAbilityPast` model and updated the example resource for Clefairy to include one if its past abilities. The example entry was its previously empty third (hidden) slot ability, listed as `null`.
> Add PokemonAbilityPast documentation and an example entry for Clefairy
